# Generated by Django 5.0 on 2023-12-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=500, unique=True)),
                ('password_hash', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
