# Generated by Django 5.0 on 2023-12-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0002_user_updated_at_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('MF', 'Mutual Funds'), ('EQ', 'Equity'), ('FO', 'Futures & Options'), ('CMD', 'Commodity')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('purchase_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCen.user')),
            ],
        ),
    ]
