# Generated by Django 5.0 on 2023-12-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0005_user_first_name_user_is_activated_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=500)),
                ('trigger_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_triggered', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCen.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCen.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tracnsaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCen.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinCen.user')),
            ],
        ),
    ]
