# Generated by Django 5.0 on 2023-12-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0006_alerts_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tracnsaction_id',
            new_name='transaction_id',
        ),
    ]
