# Generated by Django 5.0 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0007_rename_tracnsaction_id_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='alert_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
