# Generated by Django 5.0 on 2023-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0008_alter_alerts_alert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='123', max_length=500),
            preserve_default=False,
        ),
    ]
