# Generated by Django 5.0 on 2023-12-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0009_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
