# Generated by Django 5.0 on 2023-12-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinCen', '0010_alter_user_is_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
